# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Usuario/Desktop/UNI_UPC/TFG/pynq-z2_v1.0.xdc/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/BD_PWM/BD_PWM.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_PWM || ORIG_REF_NAME==BD_PWM} -quiet] -quiet

# IP: bd/BD_PWM/ip/BD_PWM_processing_system7_0_0/BD_PWM_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_PWM_processing_system7_0_0 || ORIG_REF_NAME==BD_PWM_processing_system7_0_0} -quiet] -quiet

# IP: bd/BD_PWM/ip/BD_PWM_PWM_generator_0_1/BD_PWM_PWM_generator_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_PWM_PWM_generator_0_1 || ORIG_REF_NAME==BD_PWM_PWM_generator_0_1} -quiet] -quiet

# XDC: c:/Users/Usuario/Desktop/FPGA PYNQ_Z2 PROJECTES/PWM/PWM.gen/sources_1/bd/BD_PWM/BD_PWM_ooc.xdc
