# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Usuario/Desktop/FPGA PYNQ_Z2 PROJECTES/PWM/PWM.srcs/sources_1/bd/BD_PWM/ip/BD_PWM_processing_system7_0_0/BD_PWM_processing_system7_0_0.xci
# IP: The module: 'BD_PWM_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Usuario/Desktop/FPGA PYNQ_Z2 PROJECTES/PWM/PWM.gen/sources_1/bd/BD_PWM/ip/BD_PWM_processing_system7_0_0/BD_PWM_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_PWM_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Usuario/Desktop/FPGA PYNQ_Z2 PROJECTES/PWM/PWM.srcs/sources_1/bd/BD_PWM/ip/BD_PWM_processing_system7_0_0/BD_PWM_processing_system7_0_0.xci
# IP: The module: 'BD_PWM_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Usuario/Desktop/FPGA PYNQ_Z2 PROJECTES/PWM/PWM.gen/sources_1/bd/BD_PWM/ip/BD_PWM_processing_system7_0_0/BD_PWM_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_PWM_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
