# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrains.xdc

# Block Designs: bd/clk_divider_bd/clk_divider_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_divider_bd || ORIG_REF_NAME==clk_divider_bd} -quiet] -quiet

# IP: bd/clk_divider_bd/ip/clk_divider_bd_ClockDivider_0_0/clk_divider_bd_ClockDivider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_divider_bd_ClockDivider_0_0 || ORIG_REF_NAME==clk_divider_bd_ClockDivider_0_0} -quiet] -quiet

# XDC: c:/Users/Usuario/Desktop/FPGA PYNQ_Z2 PROJECTES/CLK_PL/CLK_PL.gen/sources_1/bd/clk_divider_bd/clk_divider_bd_ooc.xdc
