# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constarins_dist_leds.xdc

# Block Designs: bd/bs_distane_leds/bs_distane_leds.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bs_distane_leds || ORIG_REF_NAME==bs_distane_leds} -quiet] -quiet

# IP: bd/bs_distane_leds/ip/bs_distane_leds_HCRS04_0_0/bs_distane_leds_HCRS04_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bs_distane_leds_HCRS04_0_0 || ORIG_REF_NAME==bs_distane_leds_HCRS04_0_0} -quiet] -quiet

# XDC: c:/Users/Usuario/Desktop/distancia_leds/distancia_leds/distancia_leds.gen/sources_1/bd/bs_distane_leds/bs_distane_leds_ooc.xdc
