# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrains_lcd.xdc

# Block Designs: bd/BD_LCD/BD_LCD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_LCD || ORIG_REF_NAME==BD_LCD} -quiet] -quiet

# IP: bd/BD_LCD/ip/BD_LCD_Text_sender_0_0/BD_LCD_Text_sender_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_LCD_Text_sender_0_0 || ORIG_REF_NAME==BD_LCD_Text_sender_0_0} -quiet] -quiet

# IP: bd/BD_LCD/ip/BD_LCD_lcd_controller_0_0/BD_LCD_lcd_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_LCD_lcd_controller_0_0 || ORIG_REF_NAME==BD_LCD_lcd_controller_0_0} -quiet] -quiet

# XDC: c:/Users/Usuario/Desktop/LCD/LCD.gen/sources_1/bd/BD_LCD/BD_LCD_ooc.xdc
